name: run-tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [7.3, 7.4, 8.0]
        laravel: [6, 7, 8, 9]
        dependency-version: [prefer-lowest, prefer-stable]

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
      -   name: Checkout code
          uses: actions/checkout@v2

      -   name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php }}
      -   name: Start Redis
          uses: supercharge/redis-github-action@1.1.0
      -   name: Install dependencies
          run: composer require "laravel/framework:${{ matrix.laravel }}"
      -   name: Execute tests
          run: vendor/bin/phpunit

  php-cs-fixer:
    name: Code style (php-cs-fixer)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install php-cs-fixer
        run: composer global require friendsofphp/php-cs-fixer
      - name: Run php-cs-fixer
        run: $HOME/.composer/vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.php
      - name: Commit changes from php-cs-fixer
        uses: EndBug/add-and-commit@v5
        with:
          author_name: Samuel Štancl
          author_email: samuel.stancl@gmail.com
          message: Fix code style (php-cs-fixer)
